//
// Generated file, do not edit! Created by nedtool 5.0 from AppMessage.msg.
//

#ifndef __APPMESSAGE_M_H
#define __APPMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>AppMessage.msg:1</tt> by nedtool.
 * <pre>
 * packet AppMessage
 * {
 *     simtime_t timeStamp;//message generate simulation time
 *     int senderId;//node identification of the (TransmitterNode.nodeIdentifier)
 *     int sequenceNumber;//current value of (seqno)(copy from PacketGenerator.seqno),then seqno++
 *     int msgSize;//message size in bytes(from PacketGenerator.messageSize)
 * }
 * </pre>
 */
class AppMessage : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::simtime_t timeStamp;
    int senderId;
    int sequenceNumber;
    int msgSize;

  private:
    void copy(const AppMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AppMessage&);

  public:
    AppMessage(const char *name=nullptr, int kind=0);
    AppMessage(const AppMessage& other);
    virtual ~AppMessage();
    AppMessage& operator=(const AppMessage& other);
    virtual AppMessage *dup() const {return new AppMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual ::omnetpp::simtime_t getTimeStamp() const;
    virtual void setTimeStamp(::omnetpp::simtime_t timeStamp);
    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);
    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);
    virtual int getMsgSize() const;
    virtual void setMsgSize(int msgSize);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AppMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AppMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __APPMESSAGE_M_H

