//
// Generated file, do not edit! Created by nedtool 5.0 from CSRequestMessage.msg.
//

#ifndef __CSREQUESTMESSAGE_M_H
#define __CSREQUESTMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>CSRequestMessage.msg:1</tt> by nedtool.
 * <pre>
 * packet CSRequestMessage
 * {
 * }
 * </pre>
 */
class CSRequestMessage : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const CSRequestMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CSRequestMessage&);

  public:
    CSRequestMessage(const char *name=nullptr, int kind=0);
    CSRequestMessage(const CSRequestMessage& other);
    virtual ~CSRequestMessage();
    CSRequestMessage& operator=(const CSRequestMessage& other);
    virtual CSRequestMessage *dup() const {return new CSRequestMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CSRequestMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CSRequestMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CSREQUESTMESSAGE_M_H

