//
// Generated file, do not edit! Created by nedtool 5.0 from SignalStopMessage.msg.
//

#ifndef __SIGNALSTOPMESSAGE_M_H
#define __SIGNALSTOPMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>SignalStopMessage.msg:2</tt> by nedtool.
 * <pre>
 * packet SignalStopMessage
 * {
 *     int identifier;
 * }
 * </pre>
 */
class SignalStopMessage : public ::omnetpp::cPacket
{
  protected:
    int identifier;

  private:
    void copy(const SignalStopMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SignalStopMessage&);

  public:
    SignalStopMessage(const char *name=nullptr, int kind=0);
    SignalStopMessage(const SignalStopMessage& other);
    virtual ~SignalStopMessage();
    SignalStopMessage& operator=(const SignalStopMessage& other);
    virtual SignalStopMessage *dup() const {return new SignalStopMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getIdentifier() const;
    virtual void setIdentifier(int identifier);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SignalStopMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SignalStopMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SIGNALSTOPMESSAGE_M_H

