//
// Generated file, do not edit! Created by nedtool 5.0 from TransmissionRequestMessage.msg.
//

#ifndef __TRANSMISSIONREQUESTMESSAGE_M_H
#define __TRANSMISSIONREQUESTMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>TransmissionRequestMessage.msg:2</tt> by nedtool.
 * <pre>
 * packet TransmissionRequestMessage
 * {
 * }
 * </pre>
 */
class TransmissionRequestMessage : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const TransmissionRequestMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TransmissionRequestMessage&);

  public:
    TransmissionRequestMessage(const char *name=nullptr, int kind=0);
    TransmissionRequestMessage(const TransmissionRequestMessage& other);
    virtual ~TransmissionRequestMessage();
    TransmissionRequestMessage& operator=(const TransmissionRequestMessage& other);
    virtual TransmissionRequestMessage *dup() const {return new TransmissionRequestMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TransmissionRequestMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TransmissionRequestMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TRANSMISSIONREQUESTMESSAGE_M_H

