//
// Generated file, do not edit! Created by nedtool 5.0 from TransmissionHigherLayerMessage.msg.
//

#ifndef __TRANSMISSIONHIGHERLAYERMESSAGE_M_H
#define __TRANSMISSIONHIGHERLAYERMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>TransmissionHigherLayerMessage.msg:2</tt> by nedtool.
 * <pre>
 * packet TransmissionHigherLayerMessage
 * {
 * }
 * </pre>
 */
class TransmissionHigherLayerMessage : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const TransmissionHigherLayerMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TransmissionHigherLayerMessage&);

  public:
    TransmissionHigherLayerMessage(const char *name=nullptr, int kind=0);
    TransmissionHigherLayerMessage(const TransmissionHigherLayerMessage& other);
    virtual ~TransmissionHigherLayerMessage();
    TransmissionHigherLayerMessage& operator=(const TransmissionHigherLayerMessage& other);
    virtual TransmissionHigherLayerMessage *dup() const {return new TransmissionHigherLayerMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TransmissionHigherLayerMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TransmissionHigherLayerMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TRANSMISSIONHIGHERLAYERMESSAGE_M_H

